### ISSUE TITLE
Stop worker gracefully

### ISSUE THREAD

**Issue by ghost** [mmoreram/GearmanBundle#134]
Hi,

I've got a problem with new deployment when a worker code change. My code base has change but the worker is still alive. Then i need to tell the worker to quit after a deployment and supervisor will restart it.

I saw an article that call about that http://dpb587.me/blog/2013/01/14/terminating-gearman-workers-in-php.html, do you think we could add it to the bundle as a feature ?

**Comment by jamesrgrinter** [comment]
agreed, this would be hugely useful. We use Capifony to deploy new versions, so either something that is relatively easy for the deploy script to do, e.g. executing a command in the old environment, or better yet the worker processes detecting that they are no longer the "current" versions and exiting. Otherwise, if there's a worker/job interface change then it needs to be deployed very carefully. 

For *nix, a signal handler that gives it the opportunity to finish (or abort) the current job would be good too (i.e. SIGTERM). That way a clean system shutdown would "do the right thing" as well.

**Comment by gcavana** [comment]
Hi @jamesrgrinter, we are working on it at LaFourchette to catch *nix signal for graceful shutdown, but there is a dependency on this PR https://github.com/mmoreram/GearmanBundle/pull/138

**Comment by chyzas** [comment]
Hi, @gcavana I see that PR #138 has been merged. Are you going create a PR to finish graceful shutdown?

**Comment by daum** [comment]
@gcavana  or anyone working on this? It'd a great addition to this bundle.  If not I can try to take a look into it.

**Comment by mmoreram** [comment]
@daum will work on that.
He is a collaborator of the project now :)

**Comment by daum** [comment]
Just an update here - it seems to be a little bit more complicated.  Locally I've gotten this working so jobs will run and then it will stop it from going into the ->work() cycle again if a SIGTERM/HUP signal has been sent.

This solves the majority of the problem, but leaves one other one.  If you have a worker which isn't doing any work the signal handler is blocked by the gearman->work() process.  So until a new job came through it wouldn't restart the worker.  

Will have to see if there is a way for it to intercept the signal and break out of the ->work() process without a new job coming.  Right now doesn't look promising.

**Comment by daum** [comment]
Looks like using a setTimeout on the worker will interrupt the work() block.  Will work on testing this out later today hopefully.
